In [1]:
import pandas as pd
import numpy as np
import random
"""
1. read all possible features
2. convert 't' and 'f' to 1 and 0
3. convert 'location' and 'text' to value (in future)
4. save as X.csv for training data
"""
class data_processing():
    def __init__(self, path_nsproperties_apt):
        self.path_nsproperties_apt= path_nsproperties_apt

    def apt_feature(self):
        def read_apt_features(path_nsproperties_apt):
            df= pd.read_csv(path_nsproperties_apt, index_col = False)
            features= ['is_rental', 'is_commercial', 'rent', 'price', 'num_bedrooms', 'area', 'num_rooms', 
                       'num_bathrooms', 'pets', 'is_new_development','common_charges', 'is_furnished']
            df= df[features]
            
            print(path_nsproperties_apt)
            print(features)
            return df
        
        def tf2binary(df):
            #convert "t" and "f" to number 1 and 0
            def f(row):
                features= ['is_rental', 'is_commercial','is_new_development', 'is_furnished']
                for col in features:
                    if row[col]=='t': row[col]= 1
                    if row[col]=='f': row[col]= 0
                return row
            df= df.apply(f, axis=1)
            return df
        
        def save_apt_features(df):
            path_save= 'data/X.csv'
            df.to_csv(path_save, index=False)
            print(path_save)
            
        df= read_apt_features(self.path_nsproperties_apt)
        df= tf2binary(df)
        save_apt_features(df)
        
        print(df.shape)
        return df
    
path_nsproperties_apt= "../pipenv/data/nsproperties_apt_exclusive_is_available_list_on_web_nyc.csv" 
df= data_processing(path_nsproperties_apt).apt_feature()
df.head()

../pipenv/data/nsproperties_apt_exclusive_is_available_list_on_web_nyc.csv
['is_rental', 'is_commercial', 'rent', 'price', 'num_bedrooms', 'area', 'num_rooms', 'num_bathrooms', 'pets', 'is_new_development', 'common_charges', 'is_furnished']
data/X.csv
(451, 12)

,is_rental,is_commercial,rent,price,num_bedrooms,area,num_rooms,num_bathrooms,pets,is_new_development,common_charges,is_furnished
0,1,0,7495.0,NaN,1.0,NaN,3.0,1.5,5.0,0,NaN,1
1,1,0,4000.0,NaN,1.0,NaN,NaN,1.0,5.0,0,NaN,0
2,1,0,4250.0,NaN,2.0,900.0,3.0,1.0,1.0,0,NaN,0
3,1,0,5800.0,NaN,3.0,NaN,5.0,2.0,1.0,0,NaN,0
4,0,0,NaN,549000.0,0.0,NaN,1.0,1.0,1.0,0,NaN,0

In [4]:
"""
1. These traffic is fake, random generated. Hence the result is fake as well.
2. For actual traffic, the top n listings apts need to be ignored. 
   Because top n listing apts does not mean those apts are real "popular". 
3. Traffic save as Y.csv for label.
"""
class traffic2Y():
    def __init__(self, path_save):
        self.path_save= path_save
    
    def traffic2label(self):
        def generate_Y(num_sample):
            low, high= 1, 1000 # low traffic and high traffic
            list_y= [ random.randint(low, high) for _ in range(num_sample) ]    
            df = pd.Series(list_y)
            return df

        def save_y(df):
            df.to_csv(self.path_save, index=False)
            print(path_save)

        num_sample= 451
        df= generate_Y(num_sample)
        print(df.head())
        save_y(df)
    
path_save= 'data/Y.csv'    
traffic2Y(path_save).traffic2label()

0    625
1    838
2    324
3    360
4    446
dtype: int64
data/Y.csv